name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Analyze code with pylint
        run: |
          pylint $(git ls-files '*.py')
          
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest -m "unit_test"

      - name: Run integration tests
        run: |
          pytest -m "integration_test"

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Build the Docker image
        uses: actions/checkout@v3
        run: |
          docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      
